### ISSUE TITLE
Lost token

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/mo_pack-feedstock#6]
@pelson this was one of those old feedstocks and re-rendering it with the modern conda-smithy ended up removing the tokens. Not sure how to proceed here. I guess we should revert `conda-forge.yml`, right?

**Comment by ocefpaf** [comment]
Fixed in #8

**Comment by ocefpaf** [comment]
I guess it is not working yet:

https://travis-ci.org/conda-forge/mo_pack-feedstock/jobs/128620866#L615

**Comment by pelson** [comment]
> I guess it is not working yet:

No. I double checked and I set it wrong. I'll have another go! :cry:

**Comment by ocefpaf** [comment]
If you are out of time I can use a hammer and just remove the feedstock and re-add `mo_pack` :smile:

**Comment by pelson** [comment]
> If you are out of time I can use a hammer and just remove the feedstock and re-add mo_pack :smile:

Ha. That's true. No, I'll put a PR up now.

**Comment by ocefpaf** [comment]
Not yet: https://travis-ci.org/conda-forge/mo_pack-feedstock/jobs/128821668#L615

Maybe the third time is the charm :stuck_out_tongue_winking_eye:

**Comment by pelson** [comment]
> Maybe the third time is the charm :stuck_out_tongue_winking_eye:

That's more worrying. The upload line is missing from the `run_docker` script, so no wonder it isn't uploading. I'll investigate  now.

**Comment by pelson** [comment]
Turns out there was something odd in the `conda-forge.yml`.

Closed with #10
